#pragma once
// Generated by tools/prepare_environment_models.py; physical catalogue bounds.
#include <array>
namespace world::decor {
struct EnvironmentModelBounds { double width, height, front; };
inline constexpr std::array<EnvironmentModelBounds, 28> kEnvironmentBounds{{
    {5.416880131, 5.177991390, 0.468340784}, // Cliff_Face_Grey
    {3.997551203, 3.147154331, 0.103914522}, // Cliff_Face_Warm
    {0.377406776, 0.037973065, 0.000000000}, // Moss_Clump
    {1.304822803, 0.436496317, 0.000000000}, // Fern_Clump
    {4.526834011, 3.082500458, 0.000000000}, // Shrub_Dense
    {3.480949640, 2.145015478, 0.000000000}, // Shrub_Low
    {10.966198921, 16.460090637, 0.000000000}, // Hornbeam_Forest_A
    {7.183897495, 13.116522789, 0.000000000}, // Hornbeam_Forest_B
    {2.045853615, 3.397004366, 0.000000000}, // Trident_Maple
    {5.855453491, 5.213718891, 0.000000000}, // Island_Tree_A
    {6.673799515, 3.516739845, 0.000000000}, // Island_Tree_B
    {6.013642311, 4.905832291, 0.000000000}, // Small_Tree
    {26.258605957, 19.856754303, 0.000000000}, // Jacaranda_Tree
    {9.518734932, 20.817945480, 0.000000000}, // Pine_Tree
    {1.871916413, 1.741492987, 0.000000000}, // Shrub_Leafy
    {0.258783609, 0.410839468, 0.000000000}, // Shrub_Round
    {1.068997383, 0.553759038, 0.000000000}, // Rooibos_Bush
    {3.084259748, 1.010368109, 0.000000000}, // Boulder_Round
    {0.406487167, 0.145859733, 0.000000000}, // Rock_Angular
    {1.301398396, 0.567243874, 0.000000000}, // Forest_Rock_Small
    {3.366824389, 0.289531171, 0.000000000}, // Dead_Trunk
    {1.906907678, 0.577669501, 0.000000000}, // Stump_Old
    {0.180227742, 0.185007647, 0.000000000}, // Red_Mushrooms
    {5.855453491, 5.213718891, 0.000000000}, // Amber_Oak
    {10.966198921, 16.460090637, 0.000000000}, // Amber_Hornbeam
    {2.045853615, 3.397004366, 0.000000000}, // Blossom_Maple
    {6.013642311, 4.905832291, 0.000000000}, // Blossom_Birch
    {6.673799515, 3.516739845, 0.000000000}, // Dark_Oak
}};
} // namespace world::decor
